### PR TITLE
Upgrade cw1 contracts

### PR DESCRIPTION
**Pull request by uint**

### CODE REVIEW

**Review by orkunkl — APPROVED** [review]
LGTM, make sure you run and fix warnings before merging:
- `cargo fmt`
- `cargo clippy --all-targets -- -D warnings`
- `cargo schema`

**Comment by uint** [comment]
@orkunkl Fixed schemas for failing packages and the cw1 contracts. Hope I'm not going to cause conflicts with your work on the packages!

**Comment by uint** [comment]
@orkunkl Also, remember I don't currently have permissions necessary to merge this myself!

**Comment by orkunkl** [comment]
Cargo.lock needs to be updated.... This sucks.

**Comment by uint** [comment]
Rebased.

**Pull request merged**
